### ISSUE TITLE
Atualizar documento de contagem de ponto de função

### ISSUE THREAD

**Issue by kaelsilva** [eduviictor/event-manager#64]
O modelo para o documento de contagem de ponto de função pode ser encontrado clicando [**aqui**](https://docs.google.com/document/d/1s4bMbrpQt9RF6tymXvI0HHfQO14hMyL08UxmX1eH82s/edit?usp=sharing).  
Duas contagens são necessárias:
- Contagem indicativa do tamanho funcional do software;
- Contagem detalhada do tamanho funcional dos user stories (cada membro da equipe faz **uma contagem detalhada** em **um user story diferente**).  
  
Segundo o plano de iteração, **o gerente deve fazer a contagem indicativa do tamanho funcional de Projeto**.

**Comment by Ewertonslv** [comment]
* Remover duplicidade ALI Tipo_ingresso
* Inserir o nome das tabelas na contagem detalhada
* Adicionar o total de pontos na contagem detalhada
* Fazer quebra dos requisitos em partes menores
